version: '3.1'
services:
    database:
        build:
            context: .
            Dockerfile: Dockerfile_db
        environment:
            MYSQL_ROOT_PASSWORD: idp_database
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - idp_network
            - db_network
    
    script:
        build:
            context: .
            Dockerfile: Dockerfile_script
        depends_on:
            - database
        ports:
            - "5000:5000"
        networks:
            - idp_network
            - db_network
    
    dbms:
        image: adminer
        ports:
            - "8080:8080"
        networks:
            - db_network
        depends_on:
            - database

networks:
    idp_network:
        driver: bridge
    db_network:
        driver: bridge