version: "3.8"
services:
    mongodb:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        networks:
            - idp_network
            - db_network
        volumes:
            - mongo_data:/data/db
    
    script:
        build:
            context: .
            dockerfile: Dockerfile_script
        depends_on:
            - mongodb
        ports:
            - "6000:6000"
        networks:
            - idp_network
            - db_network
        environment:
            MONGO_URI: mongodb://mongodb:27017/Users
        stdin_open: false
        tty: false    
    
    dbms:
        image: mongo-express
        ports:
            - "8081:8081"
        networks:
            - idp_network
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    
    auth:
        build:
            context: ../authentication
            dockerfile: Dockerfile
        networks:
            - idp_network 
        stdin_open: true
        tty: true
    
    compiler:
        build:
            context: ../interpreter
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            - idp_network
            - db_network
        stdin_open: false
        tty: false

networks:
    idp_network:
        driver: bridge
    db_network:
        driver: bridge

volumes:
    mongo_data: {}    