version: "3.8"
services:
    database:
        build:
            context: .
            dockerfile: Dockerfile_db
        environment:
            MYSQL_DATABASE: credentials
            MYSQL_ROOT_PASSWORD: idp_database
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - idp_network
            - db_network
    script:
        build:
            context: .
            dockerfile: Dockerfile_script
        depends_on:
            - database
        ports:
            - "25000:25000"
        networks:
            - idp_network
            - db_network
        stdin_open: false
        tty: false    
    dbms:
        image: adminer
        ports:
            - "8080:8080"
        networks:
            - db_network
        depends_on:
            - database
    auth:
        build:
            context: ../authentication
            dockerfile: Dockerfile
        networks:
            - idp_network 
        stdin_open: true
        tty: true
networks:
    idp_network:
        driver: bridge
    db_network:
        driver: bridge

volumes:
    db: {}    