FROM haskell:9.6.4
RUN cabal install --lib mysql-simple
RUN cabal install --lib scotty
RUN cabal install --lib http-types
RUN cabal install --lib aeson
WORKDIR /app
COPY Main.hs ./Main.hs
COPY Makefile ./Makefile
RUN make build
CMD ["make", "run"]